__include__: [
  '../dataset/urethra10.yml',
  '../runtime.yml',
  '../base/dataloader.yml',
  '../base/optimizer.yml',
  '../base/deimv2.yml',
]


output_dir: ./outputs/urethra_deimv2_dinov3_x_640_aug-hard_pretrain_lr-6.0
  
DEIM:
  backbone: DINOv3STAs

DINOv3STAs:
  name: dinov3_vits16plus
  weights_path: /home/maxime/maxime/Ureteral-Project/DEIMv2/ckpts/dinov3_vits16plus_pretrain_lvd1689m-4057cbaa.pth
  interaction_indexes: [5,8,11]   # only need the [1/8, 1/16, 1/32]
  finetune: True
  conv_inplane: 64
  hidden_dim: 256
  
HybridEncoder:
  in_channels: [256, 256, 256]
  # intra
  hidden_dim: 256
  dim_feedforward: 1024

  # cross 
  expansion: 1.25
  depth_mult: 1.37

DEIMTransformer:
  num_layers: 6
  eval_idx: -1
  feat_channels: [256, 256, 256]
  # reg_scale: 8
  hidden_dim: 256
  dim_feedforward: 2048

optimizer:
  type: AdamW
  params: 
    -
      # except norm/bn/bias in self.dinov3
      params: '^(?=.*.dinov3)(?!.*(?:norm|bn|bias)).*$'  
      lr: 0.00000002
    -
      # including norm/bn/bias in self.dinov3
      params: '^(?=.*.dinov3)(?=.*(?:norm|bn|bias)).*$'    
      lr: 0.00000002
      weight_decay: 0.
    - 
      # including norm/bn/bias except for the self.dinov3
      params: '^(?=.*(?:sta|encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.

  lr: 0.000001
  betas: [0.9, 0.999]
  weight_decay: 0.000125

## DEIM LR-Scheduler
epoches: 29 # 72 + 2n  # Increase to search for the optimal ema

lrsheduler: flatcosine
lr_gamma: 0.5
warmup_iter: 2000
flat_epoch: 14    # 4 + epoch // 2, e.g., 40 = 4 + 72 / 2
no_aug_epoch: 4

## Dense O2O: Mosaic + Mixup + CopyBlend
train_dataloader: 
  dataset: 
    transforms:
      ops:
        - {type: Mosaic, output_size: 320, rotation_range: 10, translation_range: [0.1, 0.1], scaling_range: [0.5, 1.5],
           probability: 1.0, fill_value: 0, use_cache: True, max_cached_images: 50, random_pop: True}
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: RandomZoomOut, fill: 0}
        - {type: RandomIoUCrop, p: 0.8}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: RandomHorizontalFlip}
        - {type: Resize, size: [640, 640], }
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: Normalize, mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
      policy:
        epoch: [2, 14, 25]   # list 

  collate_fn:
    mixup_epochs: [2, 14]
    stop_epoch: 25
    copyblend_epochs: [2, 25]
    base_size_repeat: 3

  total_batch_size: 8
  single_image_per_sequence: True # or False to disable
  background_image_per_batch: 1
  inference_batch_size: null

val_dataloader:
  dataset:
    transforms:
      ops:
        - {type: Resize, size: [640, 640], }
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: Normalize, mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}
  total_batch_size: 16

distance_threshold: 144.0 # 216 * 640/1080

DEIMCriterion:
  matcher:
    # new matcher
    change_matcher: True
    iou_order_alpha: 4.0
    matcher_change_epoch: 22